"""
Data Warehouse Agent — Dual-agent collaborative architecture
         Dev Agent (dev)  <──>  QA Agent (chief architect)
         Self-correction loop (max 3 retries)
"""

import os
from datetime import datetime

from dotenv import load_dotenv

load_dotenv()

from anthropic import Anthropic

from agent_tools import execute_sql_query, get_warehouse_schema

# ---------- Trace log accumulator ----------
_trace_lines: list[str] = []
TRACE_LOG_PATH = "agent_run_trace.log"


def _emit(msg: str = "") -> None:
    """Print to terminal AND accumulate for trace log."""
    print(msg)
    _trace_lines.append(msg)

# ---------- Anthropic client (DeepSeek-compatible endpoint) ----------
client = Anthropic(
    api_key=os.environ["ANTHROPIC_API_KEY"],
    base_url=os.environ["ANTHROPIC_BASE_URL"],
)

# ---------- System prompts for two roles ----------
DEV_SYSTEM_PROMPT = (
    "你是数仓开发小弟。请根据表结构快速写出实现需求的 SQL。\n"
    "记住，关键字大写，且只输出纯 SQL，不要 Markdown 包裹。"
)

QA_SYSTEM_PROMPT = (
    "你是严苛的数仓首席架构师，拥有对高危 SQL 的**一票否决权（FATAL_REJECT）**。\n"
    "你需要对小弟写的 SQL 进行 Code Review。\n\n"
    "============================================================\n"
    "【最高优先级 — 合规红线 — 一票否决 FATAL_REJECT】\n"
    "如果 SQL 中包含以下任一行为，你必须**立刻熔断流程**：\n"
    "  (a) DROP TABLE ods_orders 或 DROP TABLE ods_users\n"
    "  (b) DELETE FROM ods_orders 或 DELETE FROM ods_users\n"
    "  (c) TRUNCATE TABLE ods_orders 或 TRUNCATE TABLE ods_users\n"
    "  (d) ALTER TABLE ods_orders ... 或 ALTER TABLE ods_users ...\n"
    "  (e) CREATE OR REPLACE TABLE ods_orders ... 或 ods_users\n"
    "  (f) UPDATE ods_orders ... 或 UPDATE ods_users ...\n"
    "这些核心原始存根表（ods_orders / ods_users）是数仓的根基，不可破坏。\n"
    "触发此红线时，**严禁提供任何修改意见**，只允许输出：\n"
    "  FATAL_REJECT: [具体拦截原因，说明企图对哪张 ODS 表做了什么]\n"
    "============================================================\n\n"
    "【常规检查项】（仅在未触发 FATAL_REJECT 时生效）\n"
    "1. 严禁使用 SELECT *；\n"
    "2. 关键字必须大写（SELECT, FROM, JOIN, GROUP BY 等）；\n"
    "3. 大表关联必须指定字段，不能盲目全表扫描；\n"
    "4. 如果是建表语句（CREATE TABLE 非 ods_ 前缀的表），必须在 CREATE 之前加上\n"
    "   DROP TABLE IF EXISTS [表名]; 确保脚本可重复执行。\n\n"
    "【返回值规范】\n"
    "  - FATAL_REJECT 触发 → 仅输出 'FATAL_REJECT: [原因]'，不提供修改建议\n"
    "  - 完全合格 → 仅输出 'PASS'\n"
    "  - 有问题 → 以 'REJECT: [具体原因]' 开头，可以给出修改意见"
)


def _extract_text(response) -> str:
    """Extract text from Anthropic response, skipping ThinkingBlock items."""
    parts = [block.text for block in response.content if block.type == "text"]
    return "".join(parts).strip()


def call_dev_agent(
    requirement: str,
    schema_text: str,
    feedback: str | None = None,
) -> str:
    """
    Dev Agent — generates SQL based on schema + requirement.

    Parameters
    ----------
    requirement : str
        The user's data warehouse requirement.
    schema_text : str
        Formatted warehouse schema text.
    feedback : str or None
        QA architect's rejection feedback (only on rework rounds).

    Returns
    -------
    str
        Pure SQL string (no markdown, uppercase keywords).
    """
    if feedback:
        user_msg = (
            f"{schema_text}\n\n"
            f"User requirement:\n{requirement}\n\n"
            f"=== QA Architect rejected your previous SQL ===\n"
            f"{feedback}\n\n"
            "Please rewrite the SQL to address ALL criticisms above. "
            "Output ONLY the corrected pure SQL, no markdown wrapping."
        )
    else:
        user_msg = (
            f"{schema_text}\n\n"
            f"User requirement:\n{requirement}"
        )

    response = client.messages.create(
        model="deepseek-v4-pro",
        max_tokens=1024,
        system=DEV_SYSTEM_PROMPT,
        messages=[{"role": "user", "content": user_msg}],
    )

    return _extract_text(response)


def call_qa_agent(generated_sql: str) -> str:
    """
    QA Agent — reviews Dev's SQL, returns PASS or REJECT.

    Parameters
    ----------
    generated_sql : str
        The SQL generated by Dev Agent.

    Returns
    -------
    str
        'PASS' if approved, or 'REJECT: ...' with detailed critique.
    """
    response = client.messages.create(
        model="deepseek-v4-pro",
        max_tokens=512,
        system=QA_SYSTEM_PROMPT,
        messages=[{"role": "user", "content": generated_sql}],
    )

    return _extract_text(response)


from typing import Any, Generator

Event = dict[str, Any]


def run_dw_agent_stream(user_requirement: str) -> Generator[Event, None, None]:
    """
    Generator variant of run_dw_agent for Streamlit / web consumption.

    Yields structured events instead of printing:
      {"type": "header",   "message": ..., "requirement": ...}
      {"type": "info",     "message": ...}
      {"type": "schema",   "message": ..., "schema": dict}
      {"type": "sql",      "message": ..., "sql": ..., "round": int}
      {"type": "verdict",  "message": ..., "round": int, "is_pass": bool}
      {"type": "done",     "message": ..., "sql": ..., "result_rows": int, "rounds": int}
      {"type": "error",    "message": ...}
    """
    MAX_RETRIES = 3

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    yield {"type": "header", "message": f"Started at {now}", "requirement": user_requirement}

    # ----- Step 1: Get schema -----
    yield {"type": "info", "message": "[Step 1] Fetching warehouse schema ..."}
    schema = get_warehouse_schema()

    schema_text_lines = ["Current warehouse tables and columns:"]
    for table, cols in schema.items():
        col_list = ", ".join(f"{c['name']} {c['type']}" for c in cols)
        schema_text_lines.append(f"  - {table}({col_list})")
    schema_text = "\n".join(schema_text_lines)
    yield {"type": "schema", "message": schema_text, "schema": schema}

    # ----- Step 2: Dev Agent first attempt -----
    yield {"type": "info", "message": "[Step 2] Dev Agent generating first SQL draft ..."}
    sql = call_dev_agent(user_requirement, schema_text)
    yield {"type": "sql", "message": "[Dev] Generated SQL:", "sql": sql, "round": 0}

    # ----- Step 3-4: QA <-> Dev loop -----
    for round_no in range(1, MAX_RETRIES + 1):
        yield {"type": "info", "message": f"[Round {round_no}] QA Architect is reviewing ..."}
        verdict = call_qa_agent(sql)

        # ── FIRST: check for FATAL_REJECT (highest priority) ──
        if verdict.strip().upper().startswith("FATAL_REJECT"):
            yield {
                "type": "fatal",
                "message": verdict,
                "round": round_no,
                "sql": sql,
            }
            return

        is_pass = verdict.strip().upper().startswith("PASS")
        yield {
            "type": "verdict",
            "message": verdict,
            "round": round_no,
            "is_pass": is_pass,
        }

        if is_pass:
            result = execute_sql_query(sql)
            updated_schema = get_warehouse_schema()
            yield {
                "type": "done",
                "message": ">>> QA Architect: APPROVED. SQL executed.",
                "sql": sql,
                "result_rows": len(result),
                "rounds": round_no,
                "updated_schema": updated_schema,
            }
            return

        # Ordinary REJECT path: feed critique back to Dev
        yield {
            "type": "info",
            "message": f">>> QA Architect REJECTED. Reworking (attempt {round_no}/{MAX_RETRIES}) ...",
        }
        sql = call_dev_agent(user_requirement, schema_text, feedback=verdict)
        yield {"type": "sql", "message": "[Dev] Revised SQL:", "sql": sql, "round": round_no}

    yield {
        "type": "error",
        "message": f"!!! Max retries ({MAX_RETRIES}) exceeded. SQL did not pass QA review.",
        "sql": sql,
    }


def run_dw_agent(user_requirement: str) -> None:
    """
    Orchestrate the dual-agent workflow with self-correction loop.

    1. Fetch warehouse schema.
    2. Dev Agent generates initial SQL.
    3. QA Agent reviews; if REJECT → Dev rewrites → repeat (max 3).
    4. On PASS → execute the SQL and persist trace log.
    """
    MAX_RETRIES = 3

    # ----- Header -----
    _emit("=" * 60)
    _emit(f"Data Warehouse Agent — Trace Log")
    _emit(f"Started at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    _emit(f"Requirement: {user_requirement}")
    _emit("=" * 60)

    # ----- Step 1: Get schema -----
    _emit("\n[Step 1] Fetching warehouse schema ...")
    schema = get_warehouse_schema()

    schema_text_lines = ["Current warehouse tables and columns:"]
    for table, cols in schema.items():
        col_list = ", ".join(f"{c['name']} {c['type']}" for c in cols)
        schema_text_lines.append(f"  - {table}({col_list})")
    schema_text = "\n".join(schema_text_lines)
    _emit(schema_text)

    # ----- Step 2: Dev Agent first attempt -----
    _emit("\n[Step 2] Dev Agent generating first SQL draft ...\n")
    sql = call_dev_agent(user_requirement, schema_text)
    _emit(f"{'─' * 40}\n[Dev] Generated SQL:\n{sql}\n{'─' * 40}")

    final_sql = ""
    outcome = ""

    # ----- Step 3-4: QA <-> Dev loop -----
    for round_no in range(1, MAX_RETRIES + 1):
        _emit(f"\n[Round {round_no}] QA Architect is reviewing ...\n")
        verdict = call_qa_agent(sql)
        _emit(f"[QA] Verdict:\n  {verdict}\n")

        # ═══════════════════════════════════════════════════════════
        # FIRST: FATAL_REJECT — compliance circuit breaker
        # ═══════════════════════════════════════════════════════════
        if verdict.strip().upper().startswith("FATAL_REJECT"):
            _emit("!" * 60)
            _emit("!!!  COMPLIANCE CIRCUIT BREAKER TRIGGERED  !!!")
            _emit("!" * 60)
            _emit("")
            _emit("  [FATAL_REJECT] QA Architect issued a one-shot veto.")
            _emit("  Reason: The SQL attempts to destroy core ODS tables.")
            _emit(f"  Detail: {verdict}")
            _emit("")
            _emit("  >>> FLOW ABORTED — the offending SQL was NOT executed. <<<")
            _emit("  >>> The SQL was NOT fed back to Dev Agent for retry. <<<")
            _emit("")
            _emit("!" * 60)
            _emit("!!!  SYSTEM HALTED — ODS TABLES PROTECTED  !!!")
            _emit("!" * 60)

            _flush_trace(verdict, "FATAL_REJECT", round_no)
            return

        if verdict.strip().upper().startswith("PASS"):
            _emit("=" * 60)
            _emit(">>> QA Architect: APPROVED. Executing SQL. <<<")
            _emit("=" * 60)
            result = execute_sql_query(sql)
            _emit(f"\n  Execution done, {len(result)} rows returned/affected.")

            final_sql = sql
            outcome = "PASS"

            # Verify new tables
            updated_schema = get_warehouse_schema()
            _emit(f"\n  Updated schema now has {len(updated_schema)} table(s):")
            for t in updated_schema:
                _emit(f"    - {t}")

            # ----- Write trace log to file -----
            _flush_trace(final_sql, outcome, round_no)
            return

        # Ordinary REJECT path: feed critique back to Dev
        _emit(f">>> QA Architect REJECTED. Reworking (attempt {round_no}/{MAX_RETRIES}) ...\n")
        sql = call_dev_agent(user_requirement, schema_text, feedback=verdict)
        _emit(f"{'─' * 40}\n[Dev] Revised SQL:\n{sql}\n{'─' * 40}")

    outcome = "FAILED"
    _emit("\n!!! Max retries exceeded. The generated SQL did not pass QA review. !!!")
    _flush_trace(sql if sql else "", outcome, MAX_RETRIES)


def _flush_trace(final_sql: str, outcome: str, rounds: int) -> None:
    """Append the final summary section and write the full trace to disk."""
    _emit("=" * 60)
    _emit(f"FINISHED at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    _emit(f"Outcome   : {outcome} (rounds: {rounds})")
    _emit(f"Final SQL :")
    _emit(f"{final_sql}")
    _emit("=" * 60)

    try:
        with open(TRACE_LOG_PATH, "w", encoding="utf-8") as f:
            f.write("\n".join(_trace_lines))
        print(f"\n[Trace log saved to: {TRACE_LOG_PATH}]")
    except OSError as e:
        print(f"\n[WARNING] Failed to write trace log: {e}")


if __name__ == "__main__":
    # Safe test — normal DWS aggregation requirement
    requirement = (
        "统计一下每个城市的用户注册量，帮我建一张叫 user_city_stat 的表。"
    )
    run_dw_agent(requirement)
