"""
Data Warehouse Agent — Dual-agent collaborative architecture
         Dev Agent (dev)  <──>  QA Agent (chief architect)
         Self-correction loop (max 3 retries)
"""

import os

from dotenv import load_dotenv

load_dotenv()

from anthropic import Anthropic

from agent_tools import execute_sql_query, get_warehouse_schema

# ---------- Anthropic client (DeepSeek-compatible endpoint) ----------
client = Anthropic(
    api_key=os.environ["ANTHROPIC_API_KEY"],
    base_url=os.environ["ANTHROPIC_BASE_URL"],
)

# ---------- System prompts for two roles ----------
DEV_SYSTEM_PROMPT = (
    "你是数仓开发小弟。请根据表结构快速写出实现需求的 SQL。\n"
    "记住，关键字大写，且只输出纯 SQL，不要 Markdown 包裹。"
)

QA_SYSTEM_PROMPT = (
    "你是严苛的数仓首席架构师。你需要对小弟写的 SQL 进行 Code Review。\n"
    "检查项：\n"
    "1. 严禁使用 SELECT *；\n"
    "2. 关键字必须大写；\n"
    "3. 大表关联必须指定字段，不能盲目全表扫描。\n"
    "如果完全合格，请只输出 'PASS'；如果有问题，请详细指出修改意见，"
    "并以 'REJECT: [具体原因]' 开头。"
)


def _extract_text(response) -> str:
    """Extract text from Anthropic response, skipping ThinkingBlock items."""
    parts = [block.text for block in response.content if block.type == "text"]
    return "".join(parts).strip()


def call_dev_agent(
    requirement: str,
    schema_text: str,
    feedback: str | None = None,
) -> str:
    """
    Dev Agent — generates SQL based on schema + requirement.

    Parameters
    ----------
    requirement : str
        The user's data warehouse requirement.
    schema_text : str
        Formatted warehouse schema text.
    feedback : str or None
        QA architect's rejection feedback (only on rework rounds).

    Returns
    -------
    str
        Pure SQL string (no markdown, uppercase keywords).
    """
    if feedback:
        user_msg = (
            f"{schema_text}\n\n"
            f"User requirement:\n{requirement}\n\n"
            f"=== QA Architect rejected your previous SQL ===\n"
            f"{feedback}\n\n"
            "Please rewrite the SQL to address ALL criticisms above. "
            "Output ONLY the corrected pure SQL, no markdown wrapping."
        )
    else:
        user_msg = (
            f"{schema_text}\n\n"
            f"User requirement:\n{requirement}"
        )

    response = client.messages.create(
        model="deepseek-v4-pro",
        max_tokens=1024,
        system=DEV_SYSTEM_PROMPT,
        messages=[{"role": "user", "content": user_msg}],
    )

    return _extract_text(response)


def call_qa_agent(generated_sql: str) -> str:
    """
    QA Agent — reviews Dev's SQL, returns PASS or REJECT.

    Parameters
    ----------
    generated_sql : str
        The SQL generated by Dev Agent.

    Returns
    -------
    str
        'PASS' if approved, or 'REJECT: ...' with detailed critique.
    """
    response = client.messages.create(
        model="deepseek-v4-pro",
        max_tokens=512,
        system=QA_SYSTEM_PROMPT,
        messages=[{"role": "user", "content": generated_sql}],
    )

    return _extract_text(response)


def run_dw_agent(user_requirement: str) -> None:
    """
    Orchestrate the dual-agent workflow with self-correction loop.

    1. Fetch warehouse schema.
    2. Dev Agent generates initial SQL.
    3. QA Agent reviews; if REJECT → Dev rewrites → repeat (max 3).
    4. On PASS → execute the SQL.
    """
    MAX_RETRIES = 3

    # ----- Step 1: Get schema -----
    print("=" * 60)
    print("[Step 1] Fetching warehouse schema ...")
    schema = get_warehouse_schema()

    schema_text_lines = ["Current warehouse tables and columns:"]
    for table, cols in schema.items():
        col_list = ", ".join(f"{c['name']} {c['type']}" for c in cols)
        schema_text_lines.append(f"  - {table}({col_list})")
    schema_text = "\n".join(schema_text_lines)
    print(schema_text)

    # ----- Step 2: Dev Agent first attempt -----
    print("\n[Step 2] Dev Agent generating first SQL draft ...\n")
    sql = call_dev_agent(user_requirement, schema_text)
    print(f"{'─' * 40}\n[Dev] Generated SQL:\n{sql}\n{'─' * 40}")

    # ----- Step 3-4: QA <-> Dev loop -----
    for round_no in range(1, MAX_RETRIES + 1):
        print(f"\n[Round {round_no}] QA Architect is reviewing ...\n")
        verdict = call_qa_agent(sql)
        print(f"[QA] Verdict:\n  {verdict}\n")

        if verdict.strip().upper().startswith("PASS"):
            print("=" * 60)
            print(">>> QA Architect: APPROVED. Executing SQL. <<<")
            print("=" * 60)
            result = execute_sql_query(sql)
            print(f"\n  Execution done, {len(result)} rows returned/affected.")

            # Verify new tables
            updated_schema = get_warehouse_schema()
            print(f"\n  Updated schema now has {len(updated_schema)} table(s):")
            for t in updated_schema:
                print(f"    - {t}")
            return

        # REJECT path: feed critique back to Dev
        print(f">>> QA Architect REJECTED. Reworking (attempt {round_no}/{MAX_RETRIES}) ...\n")
        sql = call_dev_agent(user_requirement, schema_text, feedback=verdict)
        print(f"{'─' * 40}\n[Dev] Revised SQL:\n{sql}\n{'─' * 40}")

    print("\n!!! Max retries exceeded. The generated SQL did not pass QA review. !!!")


if __name__ == "__main__":
    # "Phishing" test — likely to trigger SELECT *, testing QA's rejection mechanism
    requirement = (
        "把订单表和用户表的所有数据全部拼在一起查出来，帮我建个宽表。"
    )
    run_dw_agent(requirement)
